import type { Category, Area, CostRange } from '@/types';

export const CATEGORIES: Category[] = [
  // ターゲット
  { slug: 'target-general',      axis: 'target', label: '一般企業',            parentSlug: null, order: 10, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-retail',       axis: 'target', label: '小売・店舗ビジネス',  parentSlug: null, order: 20, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-hospitality',  axis: 'target', label: '宿泊・レジャー・娯楽', parentSlug: null, order: 30, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-education',    axis: 'target', label: '教育・スクール',      parentSlug: null, order: 40, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-medical',      axis: 'target', label: '医療・衛生・ヘルスケア', parentSlug: null, order: 50, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-public',       axis: 'target', label: '公共・大型施設',      parentSlug: null, order: 60, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-professional', axis: 'target', label: '士業・専門サービス',  parentSlug: null, order: 70, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'target-individual',   axis: 'target', label: '個人',                parentSlug: null, order: 80, seoTitle: '', seoDescription: '', isActive: true },

  // 商材 - 大分類
  { slug: 'product-ai-it',     axis: 'product', label: 'AI / IT / DX / SaaS', parentSlug: null, order: 10, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-telecom',   axis: 'product', label: '通信 / 携帯 / 光回線', parentSlug: null, order: 20, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-marketing', axis: 'product', label: '広告 / 集客 / Web制作', parentSlug: null, order: 30, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-housing',   axis: 'product', label: '住宅・エネルギー',    parentSlug: null, order: 40, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-finance',   axis: 'product', label: '金融・保険',          parentSlug: null, order: 50, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-beauty',    axis: 'product', label: '美容 / 健康',         parentSlug: null, order: 60, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-food',      axis: 'product', label: '飲料 / 食品',         parentSlug: null, order: 70, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-other',     axis: 'product', label: 'その他商材',          parentSlug: null, order: 80, seoTitle: '', seoDescription: '', isActive: true },

  // 商材 - サブ
  { slug: 'product-ai',        axis: 'product', label: 'AI',          parentSlug: 'product-ai-it',    order: 11, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-dx',        axis: 'product', label: 'DX',          parentSlug: 'product-ai-it',    order: 12, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-saas',      axis: 'product', label: 'SaaS',        parentSlug: 'product-ai-it',    order: 13, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-iot',       axis: 'product', label: 'IoT',         parentSlug: 'product-ai-it',    order: 14, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-security',  axis: 'product', label: 'セキュリティ', parentSlug: 'product-ai-it',    order: 15, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-mobile',         axis: 'product', label: '携帯キャリア', parentSlug: 'product-telecom',   order: 21, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-hikari',         axis: 'product', label: '光回線',       parentSlug: 'product-telecom',   order: 22, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-corporate-line', axis: 'product', label: '法人回線',     parentSlug: 'product-telecom',   order: 23, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-ad',             axis: 'product', label: '広告',         parentSlug: 'product-marketing', order: 31, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-seo',            axis: 'product', label: 'SEO',          parentSlug: 'product-marketing', order: 32, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-web-production', axis: 'product', label: 'Web制作',      parentSlug: 'product-marketing', order: 33, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-sns',            axis: 'product', label: 'SNS運用',      parentSlug: 'product-marketing', order: 34, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-solar',    axis: 'product', label: '太陽光・蓄電池', parentSlug: 'product-housing', order: 41, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-reform',   axis: 'product', label: 'リフォーム',     parentSlug: 'product-housing', order: 42, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-exterior', axis: 'product', label: '外構',           parentSlug: 'product-housing', order: 43, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-electric', axis: 'product', label: '電気・ガス',     parentSlug: 'product-housing', order: 44, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-insurance', axis: 'product', label: '保険',   parentSlug: 'product-finance', order: 51, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-loan',      axis: 'product', label: 'ローン', parentSlug: 'product-finance', order: 52, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-investment',axis: 'product', label: '投資',   parentSlug: 'product-finance', order: 53, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-este',         axis: 'product', label: 'エステ',   parentSlug: 'product-beauty', order: 61, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-nail',         axis: 'product', label: 'ネイル',   parentSlug: 'product-beauty', order: 62, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-hair-salon',   axis: 'product', label: '美容室',   parentSlug: 'product-beauty', order: 63, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-hair-removal', axis: 'product', label: '脱毛',     parentSlug: 'product-beauty', order: 64, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-supplement',   axis: 'product', label: 'サプリ',   parentSlug: 'product-beauty', order: 65, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-beverage',    axis: 'product', label: '飲料',     parentSlug: 'product-food', order: 71, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-food-stuff',  axis: 'product', label: '食品',     parentSlug: 'product-food', order: 72, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'product-health-food', axis: 'product', label: '健康食品', parentSlug: 'product-food', order: 73, seoTitle: '', seoDescription: '', isActive: true },

  // 探し方
  { slug: 'model-low-risk',       axis: 'model', label: '簡単・低リスクで始める', parentSlug: null, order: 10, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-high-reward',    axis: 'model', label: '報酬単価が高い',         parentSlug: null, order: 20, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-side-business',  axis: 'model', label: '副業・スモールスタート', parentSlug: null, order: 30, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-women-friendly', axis: 'model', label: '女性に人気',             parentSlug: null, order: 40, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-public-support', axis: 'model', label: '公的支援・補助金活用',   parentSlug: null, order: 50, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-franchise',      axis: 'model', label: 'フランチャイズ加盟',     parentSlug: null, order: 60, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-sales-agent',    axis: 'model', label: '販売代理店',             parentSlug: null, order: 70, seoTitle: '', seoDescription: '', isActive: true },
  { slug: 'model-referral',       axis: 'model', label: '紹介代理店',             parentSlug: null, order: 80, seoTitle: '', seoDescription: '', isActive: true },
];

const REGION_DEFS: [string, string, string[]][] = [
  ['hokkaido', '北海道',    ['hokkaido']],
  ['tohoku',   '東北',      ['aomori', 'iwate', 'miyagi', 'akita', 'yamagata', 'fukushima']],
  ['kanto',    '関東',      ['tokyo', 'kanagawa', 'saitama', 'chiba', 'ibaraki', 'tochigi', 'gunma']],
  ['chubu',    '中部',      ['niigata', 'toyama', 'ishikawa', 'fukui', 'yamanashi', 'nagano', 'gifu', 'shizuoka', 'aichi']],
  ['kansai',   '関西',      ['mie', 'shiga', 'kyoto', 'osaka', 'hyogo', 'nara', 'wakayama']],
  ['chugoku',  '中国',      ['tottori', 'shimane', 'okayama', 'hiroshima', 'yamaguchi']],
  ['shikoku',  '四国',      ['tokushima', 'kagawa', 'ehime', 'kochi']],
  ['kyushu',   '九州・沖縄', ['fukuoka', 'saga', 'nagasaki', 'kumamoto', 'oita', 'miyazaki', 'kagoshima', 'okinawa']],
];

const PREFECTURE_DEFS: [string, string, string][] = [
  ['hokkaido', '北海道',   'hokkaido'],
  ['aomori',   '青森県',   'tohoku'],
  ['iwate',    '岩手県',   'tohoku'],
  ['miyagi',   '宮城県',   'tohoku'],
  ['akita',    '秋田県',   'tohoku'],
  ['yamagata', '山形県',   'tohoku'],
  ['fukushima','福島県',   'tohoku'],
  ['tokyo',    '東京都',   'kanto'],
  ['kanagawa', '神奈川県', 'kanto'],
  ['saitama',  '埼玉県',   'kanto'],
  ['chiba',    '千葉県',   'kanto'],
  ['ibaraki',  '茨城県',   'kanto'],
  ['tochigi',  '栃木県',   'kanto'],
  ['gunma',    '群馬県',   'kanto'],
  ['niigata',  '新潟県',   'chubu'],
  ['toyama',   '富山県',   'chubu'],
  ['ishikawa', '石川県',   'chubu'],
  ['fukui',    '福井県',   'chubu'],
  ['yamanashi','山梨県',   'chubu'],
  ['nagano',   '長野県',   'chubu'],
  ['gifu',     '岐阜県',   'chubu'],
  ['shizuoka', '静岡県',   'chubu'],
  ['aichi',    '愛知県',   'chubu'],
  ['mie',      '三重県',   'kansai'],
  ['shiga',    '滋賀県',   'kansai'],
  ['kyoto',    '京都府',   'kansai'],
  ['osaka',    '大阪府',   'kansai'],
  ['hyogo',    '兵庫県',   'kansai'],
  ['nara',     '奈良県',   'kansai'],
  ['wakayama', '和歌山県', 'kansai'],
  ['tottori',  '鳥取県',   'chugoku'],
  ['shimane',  '島根県',   'chugoku'],
  ['okayama',  '岡山県',   'chugoku'],
  ['hiroshima','広島県',   'chugoku'],
  ['yamaguchi','山口県',   'chugoku'],
  ['tokushima','徳島県',   'shikoku'],
  ['kagawa',   '香川県',   'shikoku'],
  ['ehime',    '愛媛県',   'shikoku'],
  ['kochi',    '高知県',   'shikoku'],
  ['fukuoka',  '福岡県',   'kyushu'],
  ['saga',     '佐賀県',   'kyushu'],
  ['nagasaki', '長崎県',   'kyushu'],
  ['kumamoto', '熊本県',   'kyushu'],
  ['oita',     '大分県',   'kyushu'],
  ['miyazaki', '宮崎県',   'kyushu'],
  ['kagoshima','鹿児島県', 'kyushu'],
  ['okinawa',  '沖縄県',   'kyushu'],
];

export const AREAS: Area[] = [
  // 全国（特殊）
  {
    slug: 'all', label: '全国', type: 'region', parentSlug: null,
    prefectures: [], order: 0,
    seoTitle: '', seoDescription: '', isActive: true,
  },
  ...REGION_DEFS.map(([slug, label, prefs], i) => ({
    slug, label, type: 'region' as const, parentSlug: null,
    prefectures: prefs, order: (i + 1) * 10,
    seoTitle: '', seoDescription: '', isActive: true,
  })),
  ...PREFECTURE_DEFS.map(([slug, label, region], i) => ({
    slug, label, type: 'prefecture' as const, parentSlug: region,
    prefectures: [], order: (i + 1) * 10,
    seoTitle: '', seoDescription: '', isActive: true,
  })),
];

export const COST_RANGES: CostRange[] = [
  { slug: 'initial-free',     label: '初期費用無料',  type: 'initial_cost', min: 0,         max: 0,          order: 10, seoTitle: '', isActive: true },
  { slug: 'initial-under100', label: '100万円以下',   type: 'initial_cost', min: 1,         max: 1_000_000,  order: 20, seoTitle: '', isActive: true },
  { slug: 'initial-under300', label: '300万円以下',   type: 'initial_cost', min: 1_000_001, max: 3_000_000,  order: 30, seoTitle: '', isActive: true },
  { slug: 'initial-over300',  label: '300万円以上',   type: 'initial_cost', min: 3_000_001, max: null,       order: 40, seoTitle: '', isActive: true },
  { slug: 'initial-unknown',  label: '応相談',        type: 'initial_cost', min: -1,        max: null,       order: 50, seoTitle: '', isActive: true },
  { slug: 'revenue-under300',  label: '年商300万円以下',  type: 'expected_revenue', min: 0,          max: 3_000_000,  order: 10, seoTitle: '', isActive: true },
  { slug: 'revenue-under500',  label: '年商500万円以下',  type: 'expected_revenue', min: 3_000_001,  max: 5_000_000,  order: 20, seoTitle: '', isActive: true },
  { slug: 'revenue-under1000', label: '年商1000万円以下', type: 'expected_revenue', min: 5_000_001,  max: 10_000_000, order: 30, seoTitle: '', isActive: true },
  { slug: 'revenue-over1000',  label: '年商1000万円以上', type: 'expected_revenue', min: 10_000_001, max: null,       order: 40, seoTitle: '', isActive: true },
  { slug: 'revenue-unknown',   label: '応相談',           type: 'expected_revenue', min: -1,         max: null,       order: 50, seoTitle: '', isActive: true },
];
